#!/bin/bash

# path to protoc is taken fom cmake variables output
PROTOBUF_PROTOC_EXECUTABLE=/home/olli/.conan/data/protobuf/3.17.1/_/_/package/552c2b3bf89afbe4b35e735f8fa21a8845fd8025/bin/protoc
mkdir `pwd`/autogenerated.gproto-classes 2>/dev/null
for protofile in *.proto; do
 ${PROTOBUF_PROTOC_EXECUTABLE} --proto_path=`pwd` --cpp_out=`pwd`/autogenerated.gproto-classes `pwd`/${protofile}
done
